### ISSUE TITLE
Running this on Google Pixel XL 2

### ISSUE THREAD

**Issue by alexs7** [mpottinger/arcoreDepth_example#1]
Hello,

I tried running this on a google pixel 2 but I got nothing..

I assume that is expected because of the missing depth API ? but I got no errors.

**Comment by mpottinger** [comment]
Yes this is only tested on Huawei P30 Pro, and requires a phone with a TOF depth  sensor, which Pixel phone's don't have. It might work on other phones with TOF sensors on them, but the correct resolution would need to be set. 

Right now it is hardcoded for P30 Pro and doesn't automatically find the right resolution for any TOF sensor on your device.

**Comment by alexs7** [comment]
Ok thanks!
